name = "mb-shop-bot"
main = "index.js"
compatibility_date = "2026-08-18"

[triggers]
crons = ["*/1 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "mb-shop-db"
database_id = "3727d446-c8ca-441a-8230-e76f7640fe35"

[vars]
SHOP_NAME = "RUS TAY IOS STORE"
BANK_NAME = "MB Bank"
BANK_ACCOUNT_NAME = "CHU TK CUA BAN"
MIN_DEPOSIT = "10000"
PAYMENT_EXPIRE_MINUTES = "15"
ADMIN_USERNAME = "@RusTayIOS"
SUPPORT_TEXT = "Nếu cần hỗ trợ, vui lòng liên hệ Admin."
MB_TOKEN_METHOD = "POST"
MB_TRANSACTION_METHOD = "GET"
